apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
data:
  DRONE_GITHUB_CLIENT_ID: xxxxxxx     #Get this from GitHub OAUTH
  DRONE_GITHUB_CLIENT_SECRET: xxxxx #Get this from GitHub OAUTH
  DRONE_RPC_SECRET: xxxxxx           #openssl rand -hex 16
  DRONE_DATABASE_DATASOURCE: xxxxx #postgres://postgresadmin:admin123@postgres:5432/postgresdb?sslmode=disable
  DRONE_USER_CREATE: xxxxxxx #username: JHolderguru, admin: true
  DRONE_SERVER_HOST: xxxxxxxxx #drone.jon.dev